apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: thanes-lims-https-redirect
  namespace: thanes-lims
spec:
  parentRefs:
    - name: lims-gateway
      sectionName: http
  hostnames:
    - lims.siamatic.work
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
